### PR TITLE
Split Jasmine into a separate subproject from the Menodora core.

### PR DESCRIPTION
**Pull request by SamirTalwar**
Stage two of adding Mocha support, right here.

### CODE REVIEW

**Comment by scarytom** [comment]
Fine... you are going to need to update the README.md at some point you know :)

**Comment by SamirTalwar** [comment]
Ooh, good point. Will do.

**Comment by scarytom** [comment]
And the site on gh-pages come to think of it

**Comment by SamirTalwar** [comment]
Done and done.

**Pull request merged**
